### ISSUE TITLE
Support removing wallet credits when member expires

### ISSUE THREAD

**Issue by mindctrl** [restrictcontentpro/rcp-edd-wallet#1]
Customer asked about this. Will see if we get some other requests for this, but seems like a good option to have.

**Comment by nosegraze** [comment]
Would this remove _all_ funds?

**Comment by pippinsplugins** [comment]
I'm not sure I see the use case here. If a member is awarded credits for each payment they give the site, shouldn't they get to keep that credit forever?

**Comment by mindctrl** [comment]
We've only had one request that I know of, and @pippinsplugins your comment makes sense. If someone has paid, they should keep the credits. I think anyone wanting to implement this feature should do it themselves. I'm happy to close this out if you two are.

**Comment by pippinsplugins** [comment]
I agree. Closing as wontfix.
